### ISSUE TITLE
Error: Could not open socket: self signed certificate

### ISSUE THREAD

**Issue by Pavanr96** [MMPieps/MMM-Mail#8]
While starting the magic mirror, I get below error, any idea what's wrong?

 [ERROR] (node:5428) UnhandledPromiseRejectionWarning: Error: Could not open socket: self signed certificate
    at socket.onerror (/home/pi/MagicMirror/modules/MMM-Mail/node_modules/emailjs-imap-client/src/emailjs-imap-client-imap.js:157:24)
    at TCPSocket._emit (/home/pi/MagicMirror/modules/MMM-Mail/node_modules/emailjs-tcp-socket/src/emailjs-tcp-socket.js:1088:9)
    at TLSSocket.<anonymous> (/home/pi/MagicMirror/modules/MMM-Mail/node_modules/emailjs-tcp-socket/src/emailjs-tcp-socket.js:324:26)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[14.07.2021 21:58.26.450] [ERROR] (node:5428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[14.07.2021 21:58.26.453] [ERROR] (node:5428) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by VincenzoKoestler** [comment]
Same issue for me, it showed my mails for a moment the other day but now I only get only  "no unread emails".
